#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine

sudo apt-get update && sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo /etc/init.d/nginx restart
