#!/usr/bin/env bash
# configure web-02 to be identical to web-01
sudo apt update && sudo apt install nginx -y

sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i "/server_name _;/a add_header X-Served-By \
$(hostname);\nrewrite ^/ https://foobar.com permanent;" \
/etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/page_404.html

sudo sed -i '/error_page 404 /404.html;/s/404.html;/page_404.html;/' /etc/nginx/sites-available/default

sudo systemctl restart nginx
