#!/usr/bin/env bash

# Update and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Set up the custom header configuration
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $(hostname);
    location / {
        root /var/www/html;
        index index.html;
    }
}' | sudo tee /etc/nginx/sites-available/custom-header

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/custom-header /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply the changes
sudo systemctl reload nginx
